### Registar um usuário
POST http://localhost:3030/users
content-type: application/json

{
    "name": "Cezar",
    "email": "jczreper@gmail.com",
    "password": "testando",
    "weight": 68,
    "height": 175
}

### Registrar uma refeição
POST http://localhost:3030/meals
content-type: application/json

{
    "name": "Pizza",
    "description": "pizza de calabresa e queijo",
    "isDiet": true
}

### Registrar uma refeição
PUT http://localhost:3030/meals/be30da5b-d54c-4d8b-be15-d58b423ed808
content-type: application/json

{
    "name": "Pizza",
    "description": "pizza de calabresa e queijo",
    "isDiet": true
}

### Deletar uma refeição
DELETE http://localhost:3030/meals/02fdafb0-3ae8-4279-a72d-bb73c1f400b7

### Mostrar todas as refeições de um usuário
GET http://localhost:3030/meals

### Listar uma refeição especifica
GET http://localhost:3030/meals/857abfe8-7889-4dc1-90bd-6f257936a047

### Listar as métricas 
GET http://localhost:3030/meals/summary