### Registar um usuário
POST http://localhost:3030/users
content-type: application/json

{
    "name": "Cezar",
    "email": "jczra@gmail.com",
    "password": "testando",
    "weight": 68,
    "height": 175
}

### Registrar uma refeição
POST http://localhost:3030/meals
content-type: application/json
Authorization: 8b4ad155-819f-467f-9f4d-f93b1ba2d308

{
    "name": "Strogonoff",
    "description": "strogonoff de frango com batata palha",
    "isDiet": false
}

### Registrar uma refeição
PUT http://localhost:3030/meals/be30da5b-d54c-4d8b-be15-d58b423ed808
content-type: application/json
Authorization: 8b4ad155-819f-467f-9f4d-f93b1ba2d308

{
    "name": "Pizza",
    "description": "pizza de calabresa e queijo",
    "isDiet": true
}